// This file is automatically generated. Do not edit it directly.
import { createMockSupabase } from './mock-client';

// Use a mock client to bypass authentication and backend connection errors
export const supabase = createMockSupabase();